version: "3"
services:
  solara:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      - SOLARA_ROOT=/valis/solara
      - VALIS_WORKERS=4
  proxy1:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx1/conf/:/etc/nginx/conf.d/:ro
  proxy2:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx2/conf/:/etc/nginx/conf.d/:ro
